[project]
name = "mongfontbuilder"
version = "0.12.2"
description = "Python library for building standard-compatible Mongolian script fonts."
license = { text = "MIT" }
readme = "README.md"
authors = [
    { name = "Kushim Jiang", email = "kushim_jiang@outlook.com" },
    { name = "Liang Hai", email = "lianghai@gmail.com" },
]
urls.repository = "https://github.com/Kushim-Jiang/mongolian"
urls.releasenotes = "https://github.com/Kushim-Jiang/mongolian/releases"
requires-python = ">=3.10"
dependencies = [
    "cattrs>=24.1.2",
    "PyYAML>=6.0.1",
    "tptq-feacomposer>=1.11.3",
    "ufo2ft>=3.4.3",
    "ufoLib2>=0.17.1",
    "unicodedata2>=17.0.0",
]

[dependency-groups]
dev = [
    "glyphs-cli>=0.4.1;sys_platform=='darwin'",
    "glyphslib>=6.13.1",
    "pyright>=1.1.411",
    "pytest>=8.3.3",
    "ruff>=0.16.5",
    "uharfbuzz>=0.42.0",
]

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
